/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienthash;

import clienthash.ServerClient;
import interfaces.IServerHash;
import interfaces.Client;
import java.net.UnknownHostException;
import java.rmi.AlreadyBoundException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;
import interfaces.IClientHash;
import interfaces.ResponceHashServer;
import java.awt.Color;
import utils.Hashing;

/**
 *
 * @author Jorge Osvaldo perez Mendoza
 */
public class ClientView extends javax.swing.JFrame {

    private ServerClient _Server;
    private int _ClientPORT;
    private String _ClienName;

    /**
     * Creates new form ChatView
     */
    public ClientView() {
        initComponents();
        txtHash.setText(Hashing.sha256(txtMainText.getText()));
        SetEnableHeader(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pnlServer = new javax.swing.JPanel();
        lblServer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtServerName = new javax.swing.JTextField();
        txtIP_Port1 = new javax.swing.JTextField();
        btnAddServer = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        lblClientPort = new javax.swing.JLabel();
        txtPortClient = new javax.swing.JTextField();
        pnlLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlMain = new javax.swing.JPanel();
        pnlusers = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlListUsers = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        LiUsers = new javax.swing.JList<>();
        btnReload = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlHeader1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtMainText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHash = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRegex = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLogServer = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCancelHash = new javax.swing.JButton();
        btnStartHash = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTimeInit = new javax.swing.JLabel();
        lblTimeEnd = new javax.swing.JLabel();
        lblTimeMs = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(194, 216, 194));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlTitle.setBackground(pnlHeader.getBackground());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Puzzle Hash");

        txtUserName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserName.setText("User01");
        txtUserName.setToolTipText("Usuario");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nombre de Usuario");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTitleLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addContainerGap(140, Short.MAX_VALUE))
                    .addGroup(pnlTitleLayout.createSequentialGroup()
                        .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlServer.setBackground(pnlHeader.getBackground());

        lblServer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblServer.setForeground(new java.awt.Color(255, 255, 255));
        lblServer.setText("Informacion del Servidor");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("IP y Puerto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre del Servidor");

        txtServerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtServerName.setToolTipText("IP y Puerto");

        txtIP_Port1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIP_Port1.setToolTipText("IP y Puerto");

        btnAddServer.setText("Agregar Server");
        btnAddServer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddServerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlServerLayout = new javax.swing.GroupLayout(pnlServer);
        pnlServer.setLayout(pnlServerLayout);
        pnlServerLayout.setHorizontalGroup(
            pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServerLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(72, 72, 72))
                    .addGroup(pnlServerLayout.createSequentialGroup()
                        .addGroup(pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlServerLayout.createSequentialGroup()
                                .addComponent(lblServer)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlServerLayout.createSequentialGroup()
                                .addComponent(txtIP_Port1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtServerName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        pnlServerLayout.setVerticalGroup(
            pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServer)
                    .addComponent(btnAddServer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIP_Port1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(txtServerName))
                .addContainerGap())
        );

        btnStart.setBackground(new java.awt.Color(0, 204, 255));
        btnStart.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("Iniciar");
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });

        lblClientPort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClientPort.setForeground(new java.awt.Color(255, 255, 255));
        lblClientPort.setText("Puerto del Cliente");

        txtPortClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPortClient.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPortClient.setText("4321");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStart)
                        .addGap(125, 125, 125))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblClientPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPortClient, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)))
                .addComponent(pnlServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(pnlServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientPort)
                    .addComponent(txtPortClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStart)
                .addContainerGap())
        );

        txtLog.setBackground(new java.awt.Color(204, 204, 204));
        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Servers");
        jLabel3.setToolTipText("");

        pnlListUsers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LiUsers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LiUsers.setForeground(new java.awt.Color(0, 153, 153));
        LiUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        LiUsers.setToolTipText("");
        jScrollPane6.setViewportView(LiUsers);
        LiUsers.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout pnlListUsersLayout = new javax.swing.GroupLayout(pnlListUsers);
        pnlListUsers.setLayout(pnlListUsersLayout);
        pnlListUsersLayout.setHorizontalGroup(
            pnlListUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlListUsersLayout.setVerticalGroup(
            pnlListUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        btnReload.setBackground(new java.awt.Color(204, 255, 255));
        btnReload.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btnReload.setText("Recargar");
        btnReload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReloadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlusersLayout = new javax.swing.GroupLayout(pnlusers);
        pnlusers.setLayout(pnlusersLayout);
        pnlusersLayout.setHorizontalGroup(
            pnlusersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlListUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlusersLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReload))
        );
        pnlusersLayout.setVerticalGroup(
            pnlusersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlusersLayout.createSequentialGroup()
                .addGroup(pnlusersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHeader1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlHeader1.setMaximumSize(new java.awt.Dimension(788, 75));
        pnlHeader1.setMinimumSize(new java.awt.Dimension(788, 75));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ingresa Texto");

        txtMainText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMainText.setText("Hola Mundo");
        txtMainText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMainTextKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("HASH Result");

        txtHash.setEditable(false);
        txtHash.setBackground(new java.awt.Color(204, 204, 204));
        txtHash.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Exprecion a buscar (Regex)");

        txtRegex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRegex.setText("[0]{2}.*");

        javax.swing.GroupLayout pnlHeader1Layout = new javax.swing.GroupLayout(pnlHeader1);
        pnlHeader1.setLayout(pnlHeader1Layout);
        pnlHeader1Layout.setHorizontalGroup(
            pnlHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeader1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMainText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeader1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(pnlHeader1Layout.createSequentialGroup()
                        .addComponent(txtHash)
                        .addGap(18, 18, 18)
                        .addComponent(txtRegex, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlHeader1Layout.setVerticalGroup(
            pnlHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeader1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Respuestas de los servidores");

        txtLogServer.setEditable(false);
        txtLogServer.setColumns(20);
        txtLogServer.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtLogServer.setRows(5);
        jScrollPane2.setViewportView(txtLogServer);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Resultado");

        txtResult.setEditable(false);
        txtResult.setBackground(new java.awt.Color(255, 255, 255));
        txtResult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResult.setText("asdsad");
        txtResult.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Inicio");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Termino");

        btnCancelHash.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelHash.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelHash.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelHash.setText("Cancelar");
        btnCancelHash.setEnabled(false);
        btnCancelHash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelHashMouseClicked(evt);
            }
        });

        btnStartHash.setBackground(new java.awt.Color(0, 153, 204));
        btnStartHash.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnStartHash.setForeground(new java.awt.Color(255, 255, 255));
        btnStartHash.setText("Inicar");
        btnStartHash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartHashMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tiempo trascurrido");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Status");

        lblTimeInit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTimeInit.setText("N/A");

        lblTimeEnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTimeEnd.setText("N/A");

        lblTimeMs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTimeMs.setText("00 ms");

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(153, 153, 153));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Sin Iniciar");
        lblStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResult)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnStartHash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelHash))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(lblTimeInit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(lblTimeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTimeMs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelHash)
                    .addComponent(btnStartHash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimeInit)
                    .addComponent(lblTimeEnd)
                    .addComponent(lblTimeMs)
                    .addComponent(lblStatus))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlusers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlusers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        // TODO add your handling code here:
        if (!btnStart.isEnabled()) {
            return;
        }
        SetEnableHeader(false);
        if (txtUserName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Favor de elegir un nombre de usuario");
        }
        if (txtPortClient.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Favor de elegir un puerto para el cliente");
        }

        try {
            if (StartApp()) {
                SetEnableHeader(false);
                SetStatu00();
            } else {
                SetEnableHeader(true);
            }
        } catch (Exception e) {
            txtLog.append("\n" + e.getMessage());
            SetEnableHeader(true);
        }
    }//GEN-LAST:event_btnStartMouseClicked

    private void btnReloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReloadMouseClicked
        try {
            _Server.TestConnectServers();
            LoadListServers();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error al refrescar la lista", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReloadMouseClicked

    private void btnAddServerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddServerMouseClicked
        // TODO add your handling code here:                 
        btnAddServer.setVisible(false);
        try {
            if (txtIP_Port1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Favor Agregar la ip y el puerto del servidor IP:Puerto");
            } else if (txtServerName.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Favor Poner el nombre del servidor");
            } else {
                String[] args = txtIP_Port1.getText().split(":");
                if(args.length != 2){
                    JOptionPane.showMessageDialog(null, "El formato de la IP no es valido");
                }else{
                    String serveIP = args[0];
                    int servePORT = Integer.valueOf(args[1]);
                    String serveName = txtServerName.getText();
                    if (_Server.AddServer(serveName, serveIP, servePORT)) {
                        LoadListServers();
                    } else {
                        JOptionPane.showMessageDialog(null, "No fue posible agregar el servidor");
                    }                    
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error al Agregar el servidor", JOptionPane.ERROR_MESSAGE);
        }finally{
            btnAddServer.setVisible(true);
        }
    }//GEN-LAST:event_btnAddServerMouseClicked

    private void txtMainTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMainTextKeyTyped
        if (txtMainText.getText().isEmpty())
            txtHash.setText("");
        else
            txtHash.setText(Hashing.sha256(txtMainText.getText()));
    }//GEN-LAST:event_txtMainTextKeyTyped

    private void btnStartHashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartHashMouseClicked
        // TODO add your handling code here:
        SetStatu00();
        if(ValidForm()){
            SetStatu01();
            StartSearch();
        }else{
            SetStatu00();
        }
    }//GEN-LAST:event_btnStartHashMouseClicked

    private void btnCancelHashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelHashMouseClicked
        // TODO add your handling code here:
        if(_Server.getServersList().size() > 0)
            SotpServers();
        SetStatu02();       
    }//GEN-LAST:event_btnCancelHashMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> LiUsers;
    private javax.swing.JButton btnAddServer;
    private javax.swing.JButton btnCancelHash;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStartHash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblClientPort;
    private javax.swing.JLabel lblServer;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTimeEnd;
    private javax.swing.JLabel lblTimeInit;
    private javax.swing.JLabel lblTimeMs;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHeader1;
    private javax.swing.JPanel pnlListUsers;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlServer;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlusers;
    private javax.swing.JTextField txtHash;
    private javax.swing.JTextField txtIP_Port1;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextArea txtLogServer;
    private javax.swing.JTextField txtMainText;
    private javax.swing.JTextField txtPortClient;
    private javax.swing.JTextField txtRegex;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtServerName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private boolean StartApp() throws RemoteException, NotBoundException, UnknownHostException, AlreadyBoundException {

        _ClientPORT = Integer.valueOf(txtPortClient.getText());
        _ClienName = txtUserName.getText();
        _Server = new ServerClient(
                _ClientPORT,
                _ClienName,
                txtLogServer,
                this
        );
        return true;
    }

    private void SetEnableHeader(boolean b) {
        txtUserName.setEnabled(b);
        txtPortClient.setEnabled(b);
        txtIP_Port1.setEnabled(!b);
        txtServerName.setEnabled(!b);
        btnAddServer.setVisible(!b);
        btnStart.setVisible(b);
        pnlMain.setVisible(!b);
    }

    private void LoadListServers() {
        txtIP_Port1.setText("");
        txtServerName.setText("");
        ArrayList<String> model = new ArrayList<>();
        for (ServerInfo item : _Server.getServersList()) {
            model.add(item.getName());
        }
        LiUsers.setListData(model.toArray(new String[0]));
    }
    
    private boolean ValidForm() {
        if(_Server.getServersList().size() == 0){
            JOptionPane.showMessageDialog(null, "Favor de agregar algun servidor!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }else            
        if (txtMainText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor de ingresar un texto incicial!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (txtRegex.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor de ingresar un texto o exprecion a buscar!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    private void SetStatu00() {
        txtResult.setText("");
        lblTimeInit.setText("");
        lblTimeEnd.setText("");
        lblTimeMs.setText("00 ms");
        txtLogServer.setText("");
        btnStartHash.setVisible(true);        
        btnCancelHash.setVisible(false);
        lblStatus.setText("Sin Iniciar");
        lblStatus.setForeground(Color.GRAY);
        _Server.Responces = new ArrayList<>();
    }
    
    private void SetStatu01() {
        txtResult.setText("");
        lblTimeInit.setText("");
        lblTimeEnd.setText("");
        lblTimeMs.setText("00 ms");
        txtLogServer.setText("");
        btnStartHash.setVisible(false);        
        btnCancelHash.setVisible(true);
        lblStatus.setText("Esperando respuesta...");
        lblStatus.setForeground(Color.BLUE);
    }

    private void SetStatu02() {        
        btnStartHash.setVisible(true);        
        btnCancelHash.setVisible(false);
        lblStatus.setText("Cancelado");
        lblStatus.setForeground(Color.RED);
    }

    private void StartSearch() {
        char[] startKey = {0};
        char numChar = 0;
        for (ServerInfo item : _Server.getServersList()) {
            try {
                item.StartSearh(_ClienName, _ClientPORT,
                    txtMainText.getText(),
                    txtRegex.getText(),
                    startKey,
                    "Hilo Secuencial",
                    2);
                numChar++;
                char[] newStart = {numChar,0,0};
                startKey = newStart;
            } catch (Exception ex) {
                txtLog.append(item.getName()+ ": "+ex.getMessage());
            }
        }
    }

    public void SotpServers() {
        for (ServerInfo item : _Server.getServersList()) {
            try {
                item.Stop();
            } catch (Exception ex) {                
                txtLog.append(item.getName()+ ": "+ex.getMessage());
            } 
        }
    }
    
    public void SetCorrectResult(ResponceHashServer res){
        txtResult.setText(res.HashFinding);
        lblTimeInit.setText(res.StartDate.toLocalTime().toString());
        lblTimeEnd.setText(res.EndDate.toLocalTime().toString());
        lblTimeMs.setText(res.TimerEnd);
        lblStatus.setText("Success");
        lblStatus.setBackground(Color.GREEN);
        btnStartHash.setVisible(true);        
        btnCancelHash.setVisible(false);        
    }
}
